# Use the Rocky Linux 8 base image

# Update the container and install python39 python39-devel gcc then clean all cache

# Set up a symlink to use python3 as python

# Install pip via CDN https://bootstrap.pypa.io/get-pip.py

# Change the working directory as /app

# Copy requirements.txt to the Container

# Install via pip with no cache with the requirements.txt files

# Copy the entire frontend application code

# Expose the Flask port

# Command to run the Flask app via "python app.py"
