# Use the Rocky Linux 8 base image

# Update the container and install python39 python39-pip python39-devel gcc then clean all cache

# Change the working directory as /app

# Copy requirements.txt to the Container

# Install via pip with no cache with the requirements.txt files

# Copy the entire frontend application code

# Expose the Flask port

# Command to run the Flask app via "python3 app.py"
