version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:example@db/todo_app"

  frontend:
    build: ./frontend
    ports:
      - "8080:5000"
    depends_on:
      - backend
    environment:
      API_URL: "http://backend:8000"


volumes:
  db_data:
