# Use the Rocky Linux 8 base image

# Update the container and install python39 python39-pip python39-devel gcc mysql-devel then clean all cache

# Change the working directory as /app

# Copy requirements.txt to the Container 

# Install via pip with no cache with the requirements.txt files

# Copy the entire backend application code

# Expose the FastAPI port

# Command to run the FastAPI app via "uvicorn app.main:app --host 0.0.0.0 --port 8000"
